# Linear Regression - Network Throughput Prediction

**Target: Data Throughput (Mbps)**

## 1.clone repo(colab only)

In [24]:
!git clone https://github.com/MohamedAAbdullah1/NTI-Final-Project.git
%cd NTI-Final-Project

Cloning into 'NTI-Final-Project'...
remote: Enumerating objects: 98, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 98 (delta 40), reused 43 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (98/98), 3.25 MiB | 13.43 MiB/s, done.
Resolving deltas: 100% (40/40), done.
/content/NTI-Final-Project/NTI-Final-Project/NTI-Final-Project

## 2.Import

In [25]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

## 3.load data

In [26]:
df = pd.read_csv('/content/NTI-Final-Project/data/processed/processed_data.csv')

In [27]:
x_train = pd.read_csv('/content/NTI-Final-Project/data/processed/X_train.csv')
x_test = pd.read_csv('/content/NTI-Final-Project/data/processed/X_test.csv')
y_train = pd.read_csv('/content/NTI-Final-Project/data/processed/y_train.csv')
y_test = pd.read_csv('/content/NTI-Final-Project/data/processed/y_test.csv')

## 4.Identify Numerical and Categorical Features

In [28]:
x_num = x_train.select_dtypes(include='number').columns
x_cat = x_train.select_dtypes(include='object').columns

## 5.Feature Scaling

In [29]:
scaler = StandardScaler()
x_train[x_num] =scaler.fit_transform(x_train[x_num])
x_test[x_num] = scaler.transform(x_test[x_num])

## 6.Encode Categorical Features

In [30]:
encoder = LabelEncoder()
for col in x_cat :
  x_train[col] = encoder.fit_transform(x_train[col])
  x_test[col] = encoder.transform(x_test[col])

## 7.Train and Test

In [31]:
x_train

,Locality,Latitude,Longitude,Signal Strength (dBm),Latency (ms),Network Type
0,15,0.122803,1.658922,0.455476,1.124536,1
1,13,-1.144246,-0.551418,-0.001717,-1.400967,2
2,7,1.009033,-1.627639,-0.017527,0.690254,1
3,12,-0.275175,0.026706,-0.609701,0.227043,1
4,17,0.360132,0.005699,-1.071692,-0.534877,1
...,...,...,...,...,...,...
13458,16,0.348084,1.118263,-1.803606,-1.553022,2
13459,6,-0.583146,0.000026,-2.410296,-1.596276,2
13460,0,1.848304,-0.326156,0.601753,0.157445,0
13461,12,0.499845,1.111389,1.185819,1.025986,0
13462,7,0.545588,1.728655,-0.841904,-1.360444,2

In [32]:
x_test

,Locality,Latitude,Longitude,Signal Strength (dBm),Latency (ms),Network Type
0,1,1.469904,-0.629334,0.295152,-1.498868,2
1,8,-1.461209,0.183161,-0.175731,-0.606721,1
2,10,-1.197638,0.020292,0.822924,-0.496261,1
3,12,1.067176,1.316981,1.383442,1.588559,0
4,10,-1.052290,-1.627946,0.816600,-0.686536,1
...,...,...,...,...,...,...
3361,8,0.196597,0.814490,1.534931,0.130702,0
3362,11,-1.076623,0.254973,0.499363,1.033099,0
3363,16,1.683144,0.508625,-3.188492,-1.400752,2
3364,1,0.110270,0.635726,1.240348,1.089781,0
3365,5,-0.515364,-1.559032,0.926021,-0.853308,1

In [33]:
y_train

       Data Throughput (Mbps)
0                    1.054622
1                   27.746917
2                    1.389367
3                    1.905477
4                    4.013216
...                       ...
13458               51.660849
13459               61.158540
13460                2.753941
13461                2.621240
13462               51.151544

[13463 rows x 1 columns]

In [34]:
y_test

      Data Throughput (Mbps)
0                  59.288426
1                   9.045216
2                   5.414390
3                   1.215062
4                   3.782074
...                      ...
3361                2.142524
3362                1.468759
3363               11.040519
3364                2.375605
3365                3.869404

[3366 rows x 1 columns]

## 8.Build Linear Regression Model

In [35]:
lr_model = LinearRegression()

## 9.Train Model

In [36]:
lr_model.fit(x_train,y_train)

LinearRegression()

## 10.Make Predication

In [37]:
y_pred = lr_model.predict(x_test)

In [38]:
y_pred_train = lr_model.predict(x_train)

## 11.Model Evaluation

In [39]:
print(r2_score(y_test,y_pred))

0.5561470673477016

In [40]:
print(f'MAE on test data : {mean_absolute_error(y_test,y_pred)}')
print(f'MSE on test data : {mean_squared_error(y_test,y_pred)}')
print(f'RMSE on test data : {np.sqrt(mean_squared_error(y_test,y_pred))}')

MAE on test data : 13.87448103782753
MSE on test data : 298.572590203906
RMSE on test data : 17.279253172631794

In [41]:
print(f'MAE on train data : {mean_absolute_error(y_train,y_pred_train)}')
print(f'MSE on train data : {mean_squared_error(y_train,y_pred_train)}')
print(f'RMSE on train data : {np.sqrt(mean_squared_error(y_train,y_pred_train))}')

MAE on train data : 13.765664156666366
MSE on train data : 291.98257187318404
RMSE on train data : 17.087497531036664

## 12.Model Cofficients

In [42]:
intercept = lr_model.intercept_
weights = lr_model.coef_.flatten()

print(f'theta0 : {intercept}')
print()
print('Weights :')

for feature, w in zip(x_train.columns, weights):
    print(f'  {feature} : {w}')

theta0 : [-1.94347399]

Weights :
  Locality : -0.01635908445396968
  Latitude : -0.004162622341553401
  Longitude : -0.1619253171338766
  Signal Strength (dBm) : -0.0637119287206227
  Latency (ms) : -7.402198719876969
  Network Type : 18.27374286211671